id: A0A83788B
base_file: fBC13.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.873123
  last_modified_at: 2022-05-30 18:41:37.873126
