id: A0A83788B
base_file: f3022.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.818307
  last_modified_at: 2022-05-30 18:41:37.818310
