id: A0A83788B
base_file: fC5D9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.876582
  last_modified_at: 2022-05-30 18:41:37.876585
