id: A0A83788B
base_file: f89AE.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.842261
  last_modified_at: 2022-05-30 18:41:37.842264
