id: A0A83788B
base_file: fD948.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.884343
  last_modified_at: 2022-05-30 18:41:37.884346
