id: A0A83788B
base_file: f6A53.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.825479
  last_modified_at: 2022-05-30 18:41:37.825482
