id: A0A83788B
base_file: f0232.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.807280
  last_modified_at: 2022-05-30 18:41:37.807285
