id: A0A83788B
base_file: f806A.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.837581
  last_modified_at: 2022-05-30 18:41:37.837584
