id: A0A83788B
base_file: f92C6.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:41:37.849002
  last_modified_at: 2022-05-30 18:41:37.849007
